[build]
    publish=".next"
    command="npm run build"
    functions="functions"

[functions]
    directory="functions"

[dev]
    command="npm run dev"

[[plugins]]
    package = "@netlify/plugin-nextjs"